spring:
  application:
    name: emozon
  output:
    ansi:
      enabled: detect
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
    enable-spring-el-compiler: true
    mode: html
  datasource:
   url: jdbc:mysql://localhost:3306/db
   username: 
   password:
   driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate.ddl-auto: update

server:
  servlet:
    context-path: /emozon
  port: 1919

logging.file: demo.log
logging:
  file:
    max-size: 50MB
    max-history: 10
  level:
    root: info
    org.springframework: info
    org.hibernate: info
    org.hibernate.SQL: debug
    org.thymeleaf: debug
    org.thymeleaf.TemplateEngine.CONFIG: trace
    org.thymeleaf.TemplateEngine.TIMER: trace
    org.thymeleaf.TemplateEngine.cache.TEMPLATE_CACHE: trace
    com.example.demo: debug
